/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * wireless.twilio.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.infra.twilio.model;

import java.util.List;

public class RatePlan
{
    public String       sid;
    public String       unique_name;
    public String       account_sid;
    public String       friendly_name;
    public boolean      data_enabled;
    public String       data_metering;
    public int          data_limit;
    public boolean      messaging_enabled;
    public boolean      voice_enabled;
    public Boolean      national_roaming_enabled;
    public Integer      national_roaming_data_limit;
    public List<String> international_roaming;
    public Integer      international_roaming_data_limit;
    public String       date_created;
    public String       date_updated;
    public String       url;
}
