export * from './AdminTasksApi';
import { AdminTasksApi }  from './AdminTasksApi';
export * from './BackgroundActivitiesApi';
import { BackgroundActivitiesApi }  from './BackgroundActivitiesApi';
export * from './CustomerCommunicationsApi';
import { CustomerCommunicationsApi }  from './CustomerCommunicationsApi';
export * from './CustomerServiceBackupsApi';
import { CustomerServiceBackupsApi }  from './CustomerServiceBackupsApi';
export * from './CustomerServiceSecretsApi';
import { CustomerServiceSecretsApi }  from './CustomerServiceSecretsApi';
export * from './CustomerServicesApi';
import { CustomerServicesApi }  from './CustomerServicesApi';
export * from './CustomerSharedSecretsApi';
import { CustomerSharedSecretsApi }  from './CustomerSharedSecretsApi';
export * from './CustomerSharedUsersApi';
import { CustomerSharedUsersApi }  from './CustomerSharedUsersApi';
export * from './CustomersApi';
import { CustomersApi }  from './CustomersApi';
export * from './DataConnectionApi';
import { DataConnectionApi }  from './DataConnectionApi';
export * from './DeploymentAgentsApi';
import { DeploymentAgentsApi }  from './DeploymentAgentsApi';
export * from './DeploymentHostFilesApi';
import { DeploymentHostFilesApi }  from './DeploymentHostFilesApi';
export * from './DeploymentHostImagePullsApi';
import { DeploymentHostImagePullsApi }  from './DeploymentHostImagePullsApi';
export * from './DeploymentHostProvisioningApi';
import { DeploymentHostProvisioningApi }  from './DeploymentHostProvisioningApi';
export * from './DeploymentHostsApi';
import { DeploymentHostsApi }  from './DeploymentHostsApi';
export * from './DeploymentTasksApi';
import { DeploymentTasksApi }  from './DeploymentTasksApi';
export * from './DockerContainersApi';
import { DockerContainersApi }  from './DockerContainersApi';
export * from './DockerVolumesApi';
import { DockerVolumesApi }  from './DockerVolumesApi';
export * from './EnumsApi';
import { EnumsApi }  from './EnumsApi';
export * from './ExportsApi';
import { ExportsApi }  from './ExportsApi';
export * from './GitHubWebHooksApi';
import { GitHubWebHooksApi }  from './GitHubWebHooksApi';
export * from './HostsApi';
import { HostsApi }  from './HostsApi';
export * from './JobDefinitionStepsApi';
import { JobDefinitionStepsApi }  from './JobDefinitionStepsApi';
export * from './JobDefinitionsApi';
import { JobDefinitionsApi }  from './JobDefinitionsApi';
export * from './JobSourcesApi';
import { JobSourcesApi }  from './JobSourcesApi';
export * from './JobStepsApi';
import { JobStepsApi }  from './JobStepsApi';
export * from './JobsApi';
import { JobsApi }  from './JobsApi';
export * from './ManagedDirectoriesApi';
import { ManagedDirectoriesApi }  from './ManagedDirectoriesApi';
export * from './RegistryImagesApi';
import { RegistryImagesApi }  from './RegistryImagesApi';
export * from './RegistryTaggedImagesApi';
import { RegistryTaggedImagesApi }  from './RegistryTaggedImagesApi';
export * from './RepositoriesApi';
import { RepositoriesApi }  from './RepositoriesApi';
export * from './RepositoryBranchesApi';
import { RepositoryBranchesApi }  from './RepositoryBranchesApi';
export * from './RepositoryCheckoutsApi';
import { RepositoryCheckoutsApi }  from './RepositoryCheckoutsApi';
export * from './RepositoryCommitsApi';
import { RepositoryCommitsApi }  from './RepositoryCommitsApi';
export * from './RolesApi';
import { RolesApi }  from './RolesApi';
export * from './SearchApi';
import { SearchApi }  from './SearchApi';
export * from './SystemPreferencesApi';
import { SystemPreferencesApi }  from './SystemPreferencesApi';
export * from './UserPreferencesApi';
import { UserPreferencesApi }  from './UserPreferencesApi';
export * from './UsersApi';
import { UsersApi }  from './UsersApi';
export const APIS = [ AdminTasksApi, BackgroundActivitiesApi, CustomerCommunicationsApi, CustomerServiceBackupsApi, CustomerServiceSecretsApi, CustomerServicesApi, CustomerSharedSecretsApi, CustomerSharedUsersApi, CustomersApi, DataConnectionApi, DeploymentAgentsApi, DeploymentHostFilesApi, DeploymentHostImagePullsApi, DeploymentHostProvisioningApi, DeploymentHostsApi, DeploymentTasksApi, DockerContainersApi, DockerVolumesApi, EnumsApi, ExportsApi, GitHubWebHooksApi, HostsApi, JobDefinitionStepsApi, JobDefinitionsApi, JobSourcesApi, JobStepsApi, JobsApi, ManagedDirectoriesApi, RegistryImagesApi, RegistryTaggedImagesApi, RepositoriesApi, RepositoryBranchesApi, RepositoryCheckoutsApi, RepositoryCommitsApi, RolesApi, SearchApi, SystemPreferencesApi, UserPreferencesApi, UsersApi, ];
