/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Waypoint APIs
 * APIs and Definitions for the Optio3 Waypoint product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class SensorConfigForArgoHytos extends models.SensorConfig {
    constructor() {
        super();
        this.setDiscriminator("SensorConfigForArgoHytos");
    }

    getFixupPrototypeFunction() { return SensorConfigForArgoHytos.fixupPrototype; }

    static newInstance(model: Partial<SensorConfigForArgoHytos>): SensorConfigForArgoHytos {
        let obj = Object.assign(new SensorConfigForArgoHytos(), model);
        SensorConfigForArgoHytos.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<SensorConfigForArgoHytos>): SensorConfigForArgoHytos {
        if (!model) return null;
        return SensorConfigForArgoHytos.newInstance(<SensorConfigForArgoHytos> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: SensorConfigForArgoHytos) {
        models.SensorConfig.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    argohytosPort: string;

}
