FROM repo.dev.optio3.io:5000/optio3-jre-armv7-full:v11.0.8_10

ENV OPTIO3_TIMEZONE PST

# Copy external dependencies first, hoping they haven't changed.
COPY target/externalDependency/*.jar /app/

# Copy internal dependencies last, which should generate a minimal delta.
COPY target/internalDependency/*.jar /app/
COPY target/*.jar /app/

WORKDIR /app

ENTRYPOINT java -cp "*" com.optio3.infra.cli.Provisioner $*
