/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Provisioner APIs
 * APIs and Definitions for the Optio3 Provisioner product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class NetworkDestinationResponse {
    getFixupPrototypeFunction() { return NetworkDestinationResponse.fixupPrototype; }

    static newInstance(model: Partial<NetworkDestinationResponse>): NetworkDestinationResponse {
        let obj = Object.assign(new NetworkDestinationResponse(), model);
        NetworkDestinationResponse.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<NetworkDestinationResponse>): NetworkDestinationResponse {
        if (!model) return null;
        return NetworkDestinationResponse.newInstance(<NetworkDestinationResponse> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: NetworkDestinationResponse) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.NetworkDestinationResponse.prototype);

        obj.fixupFields();
    }

    fixupFields() {
    }

    result: string;

}
