/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class DeployerShutdownConfiguration {
    getFixupPrototypeFunction() { return DeployerShutdownConfiguration.fixupPrototype; }

    static newInstance(model: Partial<DeployerShutdownConfiguration>): DeployerShutdownConfiguration {
        let obj = Object.assign(new DeployerShutdownConfiguration(), model);
        DeployerShutdownConfiguration.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeployerShutdownConfiguration>): DeployerShutdownConfiguration {
        if (!model) return null;
        return DeployerShutdownConfiguration.newInstance(<DeployerShutdownConfiguration> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeployerShutdownConfiguration) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.DeployerShutdownConfiguration.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.turnOffVoltage === undefined) {
            this.turnOffVoltage = 0;
        }
        if (this.turnOnVoltage === undefined) {
            this.turnOnVoltage = 0;
        }
        if (this.turnOffDelaySeconds === undefined) {
            this.turnOffDelaySeconds = 0;
        }
        if (this.turnOnDelaySeconds === undefined) {
            this.turnOnDelaySeconds = 0;
        }
    }

    turnOffVoltage: number;

    turnOnVoltage: number;

    turnOffDelaySeconds: number;

    turnOnDelaySeconds: number;

}
