/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class DeploymentAgentUpgrade {
    getFixupPrototypeFunction() { return DeploymentAgentUpgrade.fixupPrototype; }

    static newInstance(model: Partial<DeploymentAgentUpgrade>): DeploymentAgentUpgrade {
        let obj = Object.assign(new DeploymentAgentUpgrade(), model);
        DeploymentAgentUpgrade.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeploymentAgentUpgrade>): DeploymentAgentUpgrade {
        if (!model) return null;
        return DeploymentAgentUpgrade.newInstance(<DeploymentAgentUpgrade> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeploymentAgentUpgrade) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.DeploymentAgentUpgrade.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.customer) {
            models.RecordIdentity.fixupPrototype(this.customer);
        }
        if (this.service) {
            models.RecordIdentity.fixupPrototype(this.service);
        }
        if (this.hosts) {
            for (let val of this.hosts) {
                models.RecordIdentity.fixupPrototype(val);
            }
        }
    }

    action: models.DeploymentAgentUpgradeAction;

    customer: models.RecordIdentity;

    service: models.RecordIdentity;

    hosts: Array<models.RecordIdentity>;

}
