/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class EmailMessage {
    getFixupPrototypeFunction() { return EmailMessage.fixupPrototype; }

    static newInstance(model: Partial<EmailMessage>): EmailMessage {
        let obj = Object.assign(new EmailMessage(), model);
        EmailMessage.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EmailMessage>): EmailMessage {
        if (!model) return null;
        return EmailMessage.newInstance(<EmailMessage> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EmailMessage) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.EmailMessage.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.from) {
            models.EmailRecipient.fixupPrototype(this.from);
        }
        if (this.to) {
            for (let val of this.to) {
                models.EmailRecipient.fixupPrototype(val);
            }
        }
    }

    systemGenerated: boolean;

    from: models.EmailRecipient;

    to: Array<models.EmailRecipient>;

    subject: string;

    text: string;

    html: string;

}
