/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class JobDefinitionStepForMaven extends models.JobDefinitionStep {
    constructor() {
        super();
        this.setDiscriminator("JobDefinitionStepForMaven");
    }

    static readonly RECORD_IDENTITY: string = "JobDefinitionStepForMaven";

    getFixupPrototypeFunction() { return JobDefinitionStepForMaven.fixupPrototype; }

    static newInstance(model: Partial<JobDefinitionStepForMaven>): JobDefinitionStepForMaven {
        let obj = Object.assign(new JobDefinitionStepForMaven(), model);
        JobDefinitionStepForMaven.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<JobDefinitionStepForMaven>): JobDefinitionStepForMaven {
        if (!model) return null;
        return JobDefinitionStepForMaven.newInstance(<JobDefinitionStepForMaven> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: JobDefinitionStepForMaven) {
        models.JobDefinitionStep.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    pullFrom: string;

    directory: string;

}
