/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class RegistryTaggedImage {
    static readonly RECORD_IDENTITY: string = "RegistryTaggedImage";

    getFixupPrototypeFunction() { return RegistryTaggedImage.fixupPrototype; }

    static newInstance(model: Partial<RegistryTaggedImage>): RegistryTaggedImage {
        let obj = Object.assign(new RegistryTaggedImage(), model);
        RegistryTaggedImage.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<RegistryTaggedImage>): RegistryTaggedImage {
        if (!model) return null;
        return RegistryTaggedImage.newInstance(<RegistryTaggedImage> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: RegistryTaggedImage) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.RegistryTaggedImage.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (typeof this.createdOn === "string") {
            this.createdOn = new Date(<string><any>this.createdOn);
        }
        if (typeof this.updatedOn === "string") {
            this.updatedOn = new Date(<string><any>this.updatedOn);
        }
        if (this.owningJob) {
            models.RecordIdentity.fixupPrototype(this.owningJob);
        }
        if (this.image) {
            models.RecordIdentity.fixupPrototype(this.image);
        }
    }

    sysId: string;

    createdOn: Date;

    updatedOn: Date;

    owningJob: models.RecordIdentity;

    image: models.RecordIdentity;

    tag: string;

    releaseStatus: models.RegistryImageReleaseStatus;

}
