/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class RepositoryBranch {
    static readonly RECORD_IDENTITY: string = "RepositoryBranch";

    getFixupPrototypeFunction() { return RepositoryBranch.fixupPrototype; }

    static newInstance(model: Partial<RepositoryBranch>): RepositoryBranch {
        let obj = Object.assign(new RepositoryBranch(), model);
        RepositoryBranch.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<RepositoryBranch>): RepositoryBranch {
        if (!model) return null;
        return RepositoryBranch.newInstance(<RepositoryBranch> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: RepositoryBranch) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.RepositoryBranch.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (typeof this.createdOn === "string") {
            this.createdOn = new Date(<string><any>this.createdOn);
        }
        if (typeof this.updatedOn === "string") {
            this.updatedOn = new Date(<string><any>this.updatedOn);
        }
        if (this.repository) {
            models.RecordIdentity.fixupPrototype(this.repository);
        }
        if (this.head) {
            models.RecordIdentity.fixupPrototype(this.head);
        }
    }

    sysId: string;

    createdOn: Date;

    updatedOn: Date;

    repository: models.RecordIdentity;

    name: string;

    head: models.RecordIdentity;

}
