/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class RepositoryCheckout {
    static readonly RECORD_IDENTITY: string = "RepositoryCheckout";

    getFixupPrototypeFunction() { return RepositoryCheckout.fixupPrototype; }

    static newInstance(model: Partial<RepositoryCheckout>): RepositoryCheckout {
        let obj = Object.assign(new RepositoryCheckout(), model);
        RepositoryCheckout.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<RepositoryCheckout>): RepositoryCheckout {
        if (!model) return null;
        return RepositoryCheckout.newInstance(<RepositoryCheckout> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: RepositoryCheckout) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.RepositoryCheckout.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (typeof this.createdOn === "string") {
            this.createdOn = new Date(<string><any>this.createdOn);
        }
        if (typeof this.updatedOn === "string") {
            this.updatedOn = new Date(<string><any>this.updatedOn);
        }
        if (this.owningHost) {
            models.RecordIdentity.fixupPrototype(this.owningHost);
        }
        if (this.directoryForDb) {
            models.RecordIdentity.fixupPrototype(this.directoryForDb);
        }
        if (this.directoryForWork) {
            models.RecordIdentity.fixupPrototype(this.directoryForWork);
        }
    }

    sysId: string;

    createdOn: Date;

    updatedOn: Date;

    owningHost: models.RecordIdentity;

    currentBranch: string;

    currentCommit: string;

    directoryForDb: models.RecordIdentity;

    directoryForWork: models.RecordIdentity;

}
