/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Builder APIs
 * APIs and Definitions for the Optio3 Builder product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Repository {
    static readonly RECORD_IDENTITY: string = "Repository";

    getFixupPrototypeFunction() { return Repository.fixupPrototype; }

    static newInstance(model: Partial<Repository>): Repository {
        let obj = Object.assign(new Repository(), model);
        Repository.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<Repository>): Repository {
        if (!model) return null;
        return Repository.newInstance(<Repository> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: Repository) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.Repository.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (typeof this.createdOn === "string") {
            this.createdOn = new Date(<string><any>this.createdOn);
        }
        if (typeof this.updatedOn === "string") {
            this.updatedOn = new Date(<string><any>this.updatedOn);
        }
        if (this.branches) {
            for (let val of this.branches) {
                models.RecordIdentity.fixupPrototype(val);
            }
        }
        if (this.checkouts) {
            for (let val of this.checkouts) {
                models.RecordIdentity.fixupPrototype(val);
            }
        }
    }

    sysId: string;

    createdOn: Date;

    updatedOn: Date;

    name: string;

    gitUrl: string;

    branches: Array<models.RecordIdentity>;

    checkouts: Array<models.RecordIdentity>;

}
