/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class AlertEngineValueLogicalAsset extends models.AlertEngineValueAsset {
    constructor() {
        super();
        this.setDiscriminator("AlertEngineValueLogicalAsset");
    }

    getFixupPrototypeFunction() { return AlertEngineValueLogicalAsset.fixupPrototype; }

    static newInstance(model: Partial<AlertEngineValueLogicalAsset>): AlertEngineValueLogicalAsset {
        let obj = Object.assign(new AlertEngineValueLogicalAsset(), model);
        AlertEngineValueLogicalAsset.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AlertEngineValueLogicalAsset>): AlertEngineValueLogicalAsset {
        if (!model) return null;
        return AlertEngineValueLogicalAsset.newInstance(<AlertEngineValueLogicalAsset> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AlertEngineValueLogicalAsset) {
        models.AlertEngineValueAsset.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

}
