/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class EngineValueList extends models.EngineValue {
    constructor() {
        super();
        this.setDiscriminator("EngineValueList");
    }

    getFixupPrototypeFunction() { return EngineValueList.fixupPrototype; }

    static newInstance(model: Partial<EngineValueList>): EngineValueList {
        let obj = Object.assign(new EngineValueList(), model);
        EngineValueList.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EngineValueList>): EngineValueList {
        if (!model) return null;
        return EngineValueList.newInstance(<EngineValueList> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EngineValueList) {
        models.EngineValue.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (this.length === undefined) {
            this.length = 0;
        }
    }

    length: number;

}
