/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class I2CSensorSHT3x extends models.I2CSensor {
    constructor() {
        super();
        this.setDiscriminator("I2CSensor_SHT3x");
    }

    getFixupPrototypeFunction() { return I2CSensorSHT3x.fixupPrototype; }

    static newInstance(model: Partial<I2CSensorSHT3x>): I2CSensorSHT3x {
        let obj = Object.assign(new I2CSensorSHT3x(), model);
        I2CSensorSHT3x.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<I2CSensorSHT3x>): I2CSensorSHT3x {
        if (!model) return null;
        return I2CSensorSHT3x.newInstance(<I2CSensorSHT3x> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: I2CSensorSHT3x) {
        models.I2CSensor.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

}
