/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class LocationFilterRequest extends models.AssetFilterRequest {
    constructor() {
        super();
        this.setDiscriminator("LocationFilterRequest");
    }

    getFixupPrototypeFunction() { return LocationFilterRequest.fixupPrototype; }

    static newInstance(model: Partial<LocationFilterRequest>): LocationFilterRequest {
        let obj = Object.assign(new LocationFilterRequest(), model);
        LocationFilterRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<LocationFilterRequest>): LocationFilterRequest {
        if (!model) return null;
        return LocationFilterRequest.newInstance(<LocationFilterRequest> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: LocationFilterRequest) {
        models.AssetFilterRequest.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    hasGeoFences: boolean;

}
