/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class NormalizationEngineExpressionGetMetadataString extends models.EngineExpressionFromNormalization {
    constructor() {
        super();
        this.setDiscriminator("NormalizationEngineExpressionGetMetadataString");
    }

    getFixupPrototypeFunction() { return NormalizationEngineExpressionGetMetadataString.fixupPrototype; }

    static newInstance(model: Partial<NormalizationEngineExpressionGetMetadataString>): NormalizationEngineExpressionGetMetadataString {
        let obj = Object.assign(new NormalizationEngineExpressionGetMetadataString(), model);
        NormalizationEngineExpressionGetMetadataString.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<NormalizationEngineExpressionGetMetadataString>): NormalizationEngineExpressionGetMetadataString {
        if (!model) return null;
        return NormalizationEngineExpressionGetMetadataString.newInstance(<NormalizationEngineExpressionGetMetadataString> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: NormalizationEngineExpressionGetMetadataString) {
        models.EngineExpressionFromNormalization.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    key: string;

}
