/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class NormalizationEquipment {
    getFixupPrototypeFunction() { return NormalizationEquipment.fixupPrototype; }

    static newInstance(model: Partial<NormalizationEquipment>): NormalizationEquipment {
        let obj = Object.assign(new NormalizationEquipment(), model);
        NormalizationEquipment.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<NormalizationEquipment>): NormalizationEquipment {
        if (!model) return null;
        return NormalizationEquipment.newInstance(<NormalizationEquipment> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: NormalizationEquipment) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.NormalizationEquipment.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.locations) {
            for (let val of this.locations) {
                models.NormalizationEquipmentLocation.fixupPrototype(val);
            }
        }
    }

    key: string;

    sysId: string;

    name: string;

    equipmentClassId: string;

    locations: Array<models.NormalizationEquipmentLocation>;

}
