/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * api.godaddy.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.infra.godaddy.model;

import java.util.ArrayList;
import java.util.List;

public class DomainUpdate
{

    /**
     * Whether or not the domain should be locked to prevent transfers
     */
    public Boolean      locked       = null;
    /**
     * Fully-qualified domain names for Name Servers to associate with the domain
     */
    public List<String> nameServers  = new ArrayList<String>();
    /**
     * Whether or not the domain should be configured to automatically renew
     */
    public Boolean      renewAuto    = null;
    /**
     * Reseller subaccount shopperid who can manage the domain
     */
    public String       subaccountId = null;

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DomainUpdate {\n");

        sb.append("    locked: ")
          .append(toIndentedString(locked))
          .append("\n");
        sb.append("    nameServers: ")
          .append(toIndentedString(nameServers))
          .append("\n");
        sb.append("    renewAuto: ")
          .append(toIndentedString(renewAuto))
          .append("\n");
        sb.append("    subaccountId: ")
          .append(toIndentedString(subaccountId))
          .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString()
                .replace("\n", "\n    ");
    }
}
