/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * api.godaddy.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.infra.godaddy.model;

import java.util.ArrayList;
import java.util.List;

public class ErrorLimit
{

    /**
     * Short identifier for the error, suitable for indicating the specific error within client code
     */
    public String           code          = null;
    /**
     * List of the specific fields, and the errors found with their contents
     */
    public List<ErrorField> fields        = new ArrayList<ErrorField>();
    /**
     * Human-readable, English description of the error
     */
    public String           message       = null;
    /**
     * Number of seconds to wait before attempting a similar request
     */
    public Integer          retryAfterSec = null;

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ErrorLimit {\n");

        sb.append("    code: ")
          .append(toIndentedString(code))
          .append("\n");
        sb.append("    fields: ")
          .append(toIndentedString(fields))
          .append("\n");
        sb.append("    message: ")
          .append(toIndentedString(message))
          .append("\n");
        sb.append("    retryAfterSec: ")
          .append(toIndentedString(retryAfterSec))
          .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString()
                .replace("\n", "\n    ");
    }
}
