/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * api.godaddy.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.4.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.infra.godaddy.model;

public class PlaceHolderForCodeGen
{

    public DomainStatus      domainStatus      = null;
    public DomainStatusGroup domainStatusGroup = null;
    public IncludeKind       includeKind       = null;
    public CheckType         checkType         = null;
    public SourcesKind       sourcesKind       = null;

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PlaceHolderForCodeGen {\n");

        sb.append("    domainStatus: ")
          .append(toIndentedString(domainStatus))
          .append("\n");
        sb.append("    domainStatusGroup: ")
          .append(toIndentedString(domainStatusGroup))
          .append("\n");
        sb.append("    includeKind: ")
          .append(toIndentedString(includeKind))
          .append("\n");
        sb.append("    checkType: ")
          .append(toIndentedString(checkType))
          .append("\n");
        sb.append("    sourcesKind: ")
          .append(toIndentedString(sourcesKind))
          .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString()
                .replace("\n", "\n    ");
    }
}
