export * from './AdminTasksApi';
import { AdminTasksApi }  from './AdminTasksApi';
export * from './AlertDefinitionVersionsApi';
import { AlertDefinitionVersionsApi }  from './AlertDefinitionVersionsApi';
export * from './AlertDefinitionsApi';
import { AlertDefinitionsApi }  from './AlertDefinitionsApi';
export * from './AlertsApi';
import { AlertsApi }  from './AlertsApi';
export * from './AssetRelationshipsApi';
import { AssetRelationshipsApi }  from './AssetRelationshipsApi';
export * from './AssetTimeSeriesApi';
import { AssetTimeSeriesApi }  from './AssetTimeSeriesApi';
export * from './AssetsApi';
import { AssetsApi }  from './AssetsApi';
export * from './BackgroundActivitiesApi';
import { BackgroundActivitiesApi }  from './BackgroundActivitiesApi';
export * from './DashboardDefinitionVersionsApi';
import { DashboardDefinitionVersionsApi }  from './DashboardDefinitionVersionsApi';
export * from './DashboardDefinitionsApi';
import { DashboardDefinitionsApi }  from './DashboardDefinitionsApi';
export * from './DataConnectionApi';
import { DataConnectionApi }  from './DataConnectionApi';
export * from './DataImportsApi';
import { DataImportsApi }  from './DataImportsApi';
export * from './DemoTasksApi';
import { DemoTasksApi }  from './DemoTasksApi';
export * from './DeviceElementsApi';
import { DeviceElementsApi }  from './DeviceElementsApi';
export * from './DevicesApi';
import { DevicesApi }  from './DevicesApi';
export * from './DiscoveryApi';
import { DiscoveryApi }  from './DiscoveryApi';
export * from './EnumsApi';
import { EnumsApi }  from './EnumsApi';
export * from './EventsApi';
import { EventsApi }  from './EventsApi';
export * from './ExportsApi';
import { ExportsApi }  from './ExportsApi';
export * from './GatewayProberOperationsApi';
import { GatewayProberOperationsApi }  from './GatewayProberOperationsApi';
export * from './GatewaysApi';
import { GatewaysApi }  from './GatewaysApi';
export * from './HostsApi';
import { HostsApi }  from './HostsApi';
export * from './LocationsApi';
import { LocationsApi }  from './LocationsApi';
export * from './MetricsDefinitionVersionsApi';
import { MetricsDefinitionVersionsApi }  from './MetricsDefinitionVersionsApi';
export * from './MetricsDefinitionsApi';
import { MetricsDefinitionsApi }  from './MetricsDefinitionsApi';
export * from './NetworksApi';
import { NetworksApi }  from './NetworksApi';
export * from './NormalizationsApi';
import { NormalizationsApi }  from './NormalizationsApi';
export * from './ReportDefinitionVersionsApi';
import { ReportDefinitionVersionsApi }  from './ReportDefinitionVersionsApi';
export * from './ReportDefinitionsApi';
import { ReportDefinitionsApi }  from './ReportDefinitionsApi';
export * from './ReportsApi';
import { ReportsApi }  from './ReportsApi';
export * from './RolesApi';
import { RolesApi }  from './RolesApi';
export * from './SearchApi';
import { SearchApi }  from './SearchApi';
export * from './SystemPreferencesApi';
import { SystemPreferencesApi }  from './SystemPreferencesApi';
export * from './UnitsApi';
import { UnitsApi }  from './UnitsApi';
export * from './UserGroupsApi';
import { UserGroupsApi }  from './UserGroupsApi';
export * from './UserMessagesApi';
import { UserMessagesApi }  from './UserMessagesApi';
export * from './UserPreferencesApi';
import { UserPreferencesApi }  from './UserPreferencesApi';
export * from './UsersApi';
import { UsersApi }  from './UsersApi';
export * from './WorkflowsApi';
import { WorkflowsApi }  from './WorkflowsApi';
export const APIS = [ AdminTasksApi, AlertDefinitionVersionsApi, AlertDefinitionsApi, AlertsApi, AssetRelationshipsApi, AssetTimeSeriesApi, AssetsApi, BackgroundActivitiesApi, DashboardDefinitionVersionsApi, DashboardDefinitionsApi, DataConnectionApi, DataImportsApi, DemoTasksApi, DeviceElementsApi, DevicesApi, DiscoveryApi, EnumsApi, EventsApi, ExportsApi, GatewayProberOperationsApi, GatewaysApi, HostsApi, LocationsApi, MetricsDefinitionVersionsApi, MetricsDefinitionsApi, NetworksApi, NormalizationsApi, ReportDefinitionVersionsApi, ReportDefinitionsApi, ReportsApi, RolesApi, SearchApi, SystemPreferencesApi, UnitsApi, UserGroupsApi, UserMessagesApi, UserPreferencesApi, UsersApi, WorkflowsApi, ];
