# coding: utf-8

"""
Copyright (C) 2017-2018, Optio3, Inc. All Rights Reserved.

Proprietary & Confidential Information.

Optio3 Hub APIs
APIs and Definitions for the Optio3 Hub product.

OpenAPI spec version: 1.0.0


NOTE: This class is auto generated by the swagger code generator program.
https://github.com/swagger-api/swagger-codegen.git
Do not edit the class manually.
"""

class AggregationTypeId:
    NONE = "NONE"
    SUM = "SUM"
    MEAN = "MEAN"
    MIN = "MIN"
    MAX = "MAX"
    DELTA = "DELTA"
    AVGDELTA = "AVGDELTA"
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    FIRST = "FIRST"
    LAST = "LAST"
