# coding: utf-8

"""
Copyright (C) 2017-2018, Optio3, Inc. All Rights Reserved.

Proprietary & Confidential Information.

Optio3 Hub APIs
APIs and Definitions for the Optio3 Hub product.

OpenAPI spec version: 1.0.0


NOTE: This class is auto generated by the swagger code generator program.
https://github.com/swagger-api/swagger-codegen.git
Do not edit the class manually.
"""


from pprint import pformat
from six import iteritems
import re

class AlertTableWidgetConfiguration(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, size=None, name=None, description=None, locations=None, refresh_rate_in_seconds=None, manual_font_scaling=None, font_multiplier=None, toolbar_behavior=None, filterable_ranges=None, group_by=None, rollup_type=None, alert_status_ids=None, alert_type_ids=None, alert_severity_ids=None, severity_colors=None, alert_rules=None):
        """
        AlertTableWidgetConfiguration - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'size': 'int',
            'name': 'str',
            'description': 'str',
            'locations': 'list[str]',
            'refresh_rate_in_seconds': 'int',
            'manual_font_scaling': 'bool',
            'font_multiplier': 'float',
            'toolbar_behavior': 'str',
            'filterable_ranges': 'list[FilterableTimeRange]',
            'group_by': 'str',
            'rollup_type': 'str',
            'alert_status_ids': 'list[str]',
            'alert_type_ids': 'list[str]',
            'alert_severity_ids': 'list[str]',
            'severity_colors': 'list[AlertMapSeverityColor]',
            'alert_rules': 'list[RecordIdentity]',
            'discriminator___type': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'size': 'size',
            'name': 'name',
            'description': 'description',
            'locations': 'locations',
            'refresh_rate_in_seconds': 'refreshRateInSeconds',
            'manual_font_scaling': 'manualFontScaling',
            'font_multiplier': 'fontMultiplier',
            'toolbar_behavior': 'toolbarBehavior',
            'filterable_ranges': 'filterableRanges',
            'group_by': 'groupBy',
            'rollup_type': 'rollupType',
            'alert_status_ids': 'alertStatusIDs',
            'alert_type_ids': 'alertTypeIDs',
            'alert_severity_ids': 'alertSeverityIDs',
            'severity_colors': 'severityColors',
            'alert_rules': 'alertRules',
            'discriminator___type': '__type'
        }

        self._id = id
        self._size = size
        self._name = name
        self._description = description
        self._locations = locations
        self._refresh_rate_in_seconds = refresh_rate_in_seconds
        self._manual_font_scaling = manual_font_scaling
        self._font_multiplier = font_multiplier
        self._toolbar_behavior = toolbar_behavior
        self._filterable_ranges = filterable_ranges
        self._group_by = group_by
        self._rollup_type = rollup_type
        self._alert_status_ids = alert_status_ids
        self._alert_type_ids = alert_type_ids
        self._alert_severity_ids = alert_severity_ids
        self._severity_colors = severity_colors
        self._alert_rules = alert_rules

    @property
    def discriminator___type(self):
        return "AlertTableWidgetConfiguration"

    @discriminator___type.setter
    def discriminator___type(self, discriminator):
        # Don't need to do anything
        return

    @property
    def id(self):
        """
        Gets the id of this AlertTableWidgetConfiguration.

        :return: The id of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AlertTableWidgetConfiguration.

        :param id: The id of this AlertTableWidgetConfiguration.
        :type: str
        """

        self._id = id

    @property
    def size(self):
        """
        Gets the size of this AlertTableWidgetConfiguration.

        :return: The size of this AlertTableWidgetConfiguration.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """
        Sets the size of this AlertTableWidgetConfiguration.

        :param size: The size of this AlertTableWidgetConfiguration.
        :type: int
        """

        self._size = size

    @property
    def name(self):
        """
        Gets the name of this AlertTableWidgetConfiguration.

        :return: The name of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AlertTableWidgetConfiguration.

        :param name: The name of this AlertTableWidgetConfiguration.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this AlertTableWidgetConfiguration.

        :return: The description of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this AlertTableWidgetConfiguration.

        :param description: The description of this AlertTableWidgetConfiguration.
        :type: str
        """

        self._description = description

    @property
    def locations(self):
        """
        Gets the locations of this AlertTableWidgetConfiguration.

        :return: The locations of this AlertTableWidgetConfiguration.
        :rtype: list[str]
        """
        return self._locations

    @locations.setter
    def locations(self, locations):
        """
        Sets the locations of this AlertTableWidgetConfiguration.

        :param locations: The locations of this AlertTableWidgetConfiguration.
        :type: list[str]
        """

        self._locations = locations

    @property
    def refresh_rate_in_seconds(self):
        """
        Gets the refresh_rate_in_seconds of this AlertTableWidgetConfiguration.

        :return: The refresh_rate_in_seconds of this AlertTableWidgetConfiguration.
        :rtype: int
        """
        return self._refresh_rate_in_seconds

    @refresh_rate_in_seconds.setter
    def refresh_rate_in_seconds(self, refresh_rate_in_seconds):
        """
        Sets the refresh_rate_in_seconds of this AlertTableWidgetConfiguration.

        :param refresh_rate_in_seconds: The refresh_rate_in_seconds of this AlertTableWidgetConfiguration.
        :type: int
        """

        self._refresh_rate_in_seconds = refresh_rate_in_seconds

    @property
    def manual_font_scaling(self):
        """
        Gets the manual_font_scaling of this AlertTableWidgetConfiguration.

        :return: The manual_font_scaling of this AlertTableWidgetConfiguration.
        :rtype: bool
        """
        return self._manual_font_scaling

    @manual_font_scaling.setter
    def manual_font_scaling(self, manual_font_scaling):
        """
        Sets the manual_font_scaling of this AlertTableWidgetConfiguration.

        :param manual_font_scaling: The manual_font_scaling of this AlertTableWidgetConfiguration.
        :type: bool
        """

        self._manual_font_scaling = manual_font_scaling

    @property
    def font_multiplier(self):
        """
        Gets the font_multiplier of this AlertTableWidgetConfiguration.

        :return: The font_multiplier of this AlertTableWidgetConfiguration.
        :rtype: float
        """
        return self._font_multiplier

    @font_multiplier.setter
    def font_multiplier(self, font_multiplier):
        """
        Sets the font_multiplier of this AlertTableWidgetConfiguration.

        :param font_multiplier: The font_multiplier of this AlertTableWidgetConfiguration.
        :type: float
        """

        self._font_multiplier = font_multiplier

    @property
    def toolbar_behavior(self):
        """
        Gets the toolbar_behavior of this AlertTableWidgetConfiguration.

        :return: The toolbar_behavior of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._toolbar_behavior

    @toolbar_behavior.setter
    def toolbar_behavior(self, toolbar_behavior):
        """
        Sets the toolbar_behavior of this AlertTableWidgetConfiguration.

        :param toolbar_behavior: The toolbar_behavior of this AlertTableWidgetConfiguration.
        :type: str
        """
        allowed_values = ["AlwaysShow", "AutoHide", "Collapsible", "Hide"]
        if toolbar_behavior is not None and toolbar_behavior not in allowed_values:
            raise ValueError(
                "Invalid value for `toolbar_behavior` ({0}), must be one of {1}"
                .format(toolbar_behavior, allowed_values)
            )

        self._toolbar_behavior = toolbar_behavior

    @property
    def filterable_ranges(self):
        """
        Gets the filterable_ranges of this AlertTableWidgetConfiguration.

        :return: The filterable_ranges of this AlertTableWidgetConfiguration.
        :rtype: list[FilterableTimeRange]
        """
        return self._filterable_ranges

    @filterable_ranges.setter
    def filterable_ranges(self, filterable_ranges):
        """
        Sets the filterable_ranges of this AlertTableWidgetConfiguration.

        :param filterable_ranges: The filterable_ranges of this AlertTableWidgetConfiguration.
        :type: list[FilterableTimeRange]
        """

        self._filterable_ranges = filterable_ranges

    @property
    def group_by(self):
        """
        Gets the group_by of this AlertTableWidgetConfiguration.

        :return: The group_by of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._group_by

    @group_by.setter
    def group_by(self, group_by):
        """
        Sets the group_by of this AlertTableWidgetConfiguration.

        :param group_by: The group_by of this AlertTableWidgetConfiguration.
        :type: str
        """
        allowed_values = ["location", "manufacturer", "priority", "relation", "rule", "severity", "status", "type"]
        if group_by is not None and group_by not in allowed_values:
            raise ValueError(
                "Invalid value for `group_by` ({0}), must be one of {1}"
                .format(group_by, allowed_values)
            )

        self._group_by = group_by

    @property
    def rollup_type(self):
        """
        Gets the rollup_type of this AlertTableWidgetConfiguration.

        :return: The rollup_type of this AlertTableWidgetConfiguration.
        :rtype: str
        """
        return self._rollup_type

    @rollup_type.setter
    def rollup_type(self, rollup_type):
        """
        Sets the rollup_type of this AlertTableWidgetConfiguration.

        :param rollup_type: The rollup_type of this AlertTableWidgetConfiguration.
        :type: str
        """
        allowed_values = ["ADMITTING", "APARTMENT", "ATRIUM", "AUDITORIUM", "BACKOFFICE", "BALCONY", "BAR_ROOM", "BATHROOM", "BEDROOM", "BREAK_ROOM", "BUILDING", "CABLE_ROOM", "CAFETERIA_ROOM", "CAMPUS", "CINEMA", "CLASSROOM", "CLEANING_ROOM", "CLIMATE_CONTROL_ROOM", "CLOAK_ROOM", "CONFERENCE_ROOM", "CONVERSATION_ROOM", "COOKING_ROOM", "COPYING_ROOM", "COPY_ROOM", "DATAS_ERVER_ROOM", "DELIVERY_ROOM", "DINING_ROOM", "DISTRIBUTION_CENTER", "DRESSING_ROOM", "EDUCATIONAL_ROOM", "ELECTRICAL_ROOM", "ELEVATOR", "ELEVATOR_ROOM", "ELEVATOR_SHAFT", "ENTRANCE", "EXERCISE_ROOM", "EXHIBITION_ROOM", "FACADE", "FACTORY", "FITTING_ROOM", "FLOOR", "FOOD_HANDLING_ROOM", "FRONT_DESK", "GARAGE", "GROUP_ROOM", "HALLWAY", "HOME", "HOSPITAL", "ICU", "INPATIENT_SERVICES", "KITCHEN", "LABORATORY", "LAB_SERVICES", "LAND", "LAUNDRY_ROOM", "LEVEL", "LIBRARY", "LIVING_ROOM", "LOADING_RECEIVING_ROOM", "LOBBY", "LOCKER_ROOM", "LOUNGE", "MEDITATION_ROOM", "MORGUE", "MOTHERS_ROOM", "MULTI_PURPOSE_ROOM", "NURSERY", "NURSING_FACILITY", "OFFICE", "OFFICE_ROOM", "OPERATING_ROOM", "OUTPATIENT_SERVICES", "PANTRY", "PARKING", "PERSONAL_HYGIENE", "PHARMACY", "RADIOLOGY", "RECEPTION", "RECORDING_ROOM", "RECOVERY_ROOM", "RECREATIONAL_ROOM", "REGION", "REGIONAL_CENTER", "RESTROOM", "RESTING_ROOM", "RETAIL_ROOM", "ROOF_INNER", "ROOF_OUTER", "ROOF_TOP", "ROOM", "SCHOOL", "SECTION", "SECURITY_ROOM", "SERVER_ROOM", "SERVICE_SHAFT", "SHELTER", "SHIP", "SHOPPING_MALL", "SLAB", "SMALL_STUDY_ROOM", "SPRINKLER_ROOM", "STADIUM", "STAFF_ROOM", "STAIRWELL", "STAIRS", "STORAGE", "STORAGE_ROOM", "SUB_BUILDING", "SUPPLY_ROOM", "TELECOMMUNICATION_ROOM", "TENANT_UNIT", "TERRACE", "THEATER", "THERAPY", "TRAILER", "TREATMENT_ROOM", "TREATMENT_WAITING_ROOM", "TRUCK", "UTILITIES_ROOM", "WARD", "WASTE_MANAGEMENT_ROOM", "WORKSHOP", "ZONE", "OTHER"]
        if rollup_type is not None and rollup_type not in allowed_values:
            raise ValueError(
                "Invalid value for `rollup_type` ({0}), must be one of {1}"
                .format(rollup_type, allowed_values)
            )

        self._rollup_type = rollup_type

    @property
    def alert_status_ids(self):
        """
        Gets the alert_status_ids of this AlertTableWidgetConfiguration.

        :return: The alert_status_ids of this AlertTableWidgetConfiguration.
        :rtype: list[str]
        """
        return self._alert_status_ids

    @alert_status_ids.setter
    def alert_status_ids(self, alert_status_ids):
        """
        Sets the alert_status_ids of this AlertTableWidgetConfiguration.

        :param alert_status_ids: The alert_status_ids of this AlertTableWidgetConfiguration.
        :type: list[str]
        """
        allowed_values = ["active", "muted", "resolved", "closed"]
        if not set(alert_status_ids).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `alert_status_ids` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(alert_status_ids)-set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._alert_status_ids = alert_status_ids

    @property
    def alert_type_ids(self):
        """
        Gets the alert_type_ids of this AlertTableWidgetConfiguration.

        :return: The alert_type_ids of this AlertTableWidgetConfiguration.
        :rtype: list[str]
        """
        return self._alert_type_ids

    @alert_type_ids.setter
    def alert_type_ids(self, alert_type_ids):
        """
        Sets the alert_type_ids of this AlertTableWidgetConfiguration.

        :param alert_type_ids: The alert_type_ids of this AlertTableWidgetConfiguration.
        :type: list[str]
        """
        allowed_values = ["ALARM", "COMMUNICATION_PROBLEM", "DEVICE_FAILURE", "END_OF_LIFE", "INFORMATIONAL", "OPERATOR_SUMMARY", "RECALL", "THRESHOLD_EXCEEDED", "WARNING", "WARRANTY"]
        if not set(alert_type_ids).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `alert_type_ids` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(alert_type_ids)-set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._alert_type_ids = alert_type_ids

    @property
    def alert_severity_ids(self):
        """
        Gets the alert_severity_ids of this AlertTableWidgetConfiguration.

        :return: The alert_severity_ids of this AlertTableWidgetConfiguration.
        :rtype: list[str]
        """
        return self._alert_severity_ids

    @alert_severity_ids.setter
    def alert_severity_ids(self, alert_severity_ids):
        """
        Sets the alert_severity_ids of this AlertTableWidgetConfiguration.

        :param alert_severity_ids: The alert_severity_ids of this AlertTableWidgetConfiguration.
        :type: list[str]
        """
        allowed_values = ["CRITICAL", "SIGNIFICANT", "NORMAL", "LOW"]
        if not set(alert_severity_ids).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `alert_severity_ids` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(alert_severity_ids)-set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._alert_severity_ids = alert_severity_ids

    @property
    def severity_colors(self):
        """
        Gets the severity_colors of this AlertTableWidgetConfiguration.

        :return: The severity_colors of this AlertTableWidgetConfiguration.
        :rtype: list[AlertMapSeverityColor]
        """
        return self._severity_colors

    @severity_colors.setter
    def severity_colors(self, severity_colors):
        """
        Sets the severity_colors of this AlertTableWidgetConfiguration.

        :param severity_colors: The severity_colors of this AlertTableWidgetConfiguration.
        :type: list[AlertMapSeverityColor]
        """

        self._severity_colors = severity_colors

    @property
    def alert_rules(self):
        """
        Gets the alert_rules of this AlertTableWidgetConfiguration.

        :return: The alert_rules of this AlertTableWidgetConfiguration.
        :rtype: list[RecordIdentity]
        """
        return self._alert_rules

    @alert_rules.setter
    def alert_rules(self, alert_rules):
        """
        Sets the alert_rules of this AlertTableWidgetConfiguration.

        :param alert_rules: The alert_rules of this AlertTableWidgetConfiguration.
        :type: list[RecordIdentity]
        """

        self._alert_rules = alert_rules

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AlertTableWidgetConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

