# coding: utf-8

"""
Copyright (C) 2017-2018, Optio3, Inc. All Rights Reserved.

Proprietary & Confidential Information.

Optio3 Hub APIs
APIs and Definitions for the Optio3 Hub product.

OpenAPI spec version: 1.0.0


NOTE: This class is auto generated by the swagger code generator program.
https://github.com/swagger-api/swagger-codegen.git
Do not edit the class manually.
"""


from pprint import pformat
from six import iteritems
import re

class EngineStatementLookupTablePut(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, x=None, y=None, table=None, key=None, value=None, case_insensitive=None):
        """
        EngineStatementLookupTablePut - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'x': 'int',
            'y': 'int',
            'table': 'EngineExpression',
            'key': 'EngineExpression',
            'value': 'EngineExpression',
            'case_insensitive': 'bool',
            'discriminator___type': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'x': 'x',
            'y': 'y',
            'table': 'table',
            'key': 'key',
            'value': 'value',
            'case_insensitive': 'caseInsensitive',
            'discriminator___type': '__type'
        }

        self._id = id
        self._x = x
        self._y = y
        self._table = table
        self._key = key
        self._value = value
        self._case_insensitive = case_insensitive

    @property
    def discriminator___type(self):
        return "EngineStatementLookupTablePut"

    @discriminator___type.setter
    def discriminator___type(self, discriminator):
        # Don't need to do anything
        return

    @property
    def id(self):
        """
        Gets the id of this EngineStatementLookupTablePut.

        :return: The id of this EngineStatementLookupTablePut.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this EngineStatementLookupTablePut.

        :param id: The id of this EngineStatementLookupTablePut.
        :type: str
        """

        self._id = id

    @property
    def x(self):
        """
        Gets the x of this EngineStatementLookupTablePut.

        :return: The x of this EngineStatementLookupTablePut.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x):
        """
        Sets the x of this EngineStatementLookupTablePut.

        :param x: The x of this EngineStatementLookupTablePut.
        :type: int
        """

        self._x = x

    @property
    def y(self):
        """
        Gets the y of this EngineStatementLookupTablePut.

        :return: The y of this EngineStatementLookupTablePut.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y):
        """
        Sets the y of this EngineStatementLookupTablePut.

        :param y: The y of this EngineStatementLookupTablePut.
        :type: int
        """

        self._y = y

    @property
    def table(self):
        """
        Gets the table of this EngineStatementLookupTablePut.

        :return: The table of this EngineStatementLookupTablePut.
        :rtype: EngineExpression
        """
        return self._table

    @table.setter
    def table(self, table):
        """
        Sets the table of this EngineStatementLookupTablePut.

        :param table: The table of this EngineStatementLookupTablePut.
        :type: EngineExpression
        """

        self._table = table

    @property
    def key(self):
        """
        Gets the key of this EngineStatementLookupTablePut.

        :return: The key of this EngineStatementLookupTablePut.
        :rtype: EngineExpression
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this EngineStatementLookupTablePut.

        :param key: The key of this EngineStatementLookupTablePut.
        :type: EngineExpression
        """

        self._key = key

    @property
    def value(self):
        """
        Gets the value of this EngineStatementLookupTablePut.

        :return: The value of this EngineStatementLookupTablePut.
        :rtype: EngineExpression
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this EngineStatementLookupTablePut.

        :param value: The value of this EngineStatementLookupTablePut.
        :type: EngineExpression
        """

        self._value = value

    @property
    def case_insensitive(self):
        """
        Gets the case_insensitive of this EngineStatementLookupTablePut.

        :return: The case_insensitive of this EngineStatementLookupTablePut.
        :rtype: bool
        """
        return self._case_insensitive

    @case_insensitive.setter
    def case_insensitive(self, case_insensitive):
        """
        Sets the case_insensitive of this EngineStatementLookupTablePut.

        :param case_insensitive: The case_insensitive of this EngineStatementLookupTablePut.
        :type: bool
        """

        self._case_insensitive = case_insensitive

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EngineStatementLookupTablePut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
