# coding: utf-8

"""
Copyright (C) 2017-2018, Optio3, Inc. All Rights Reserved.

Proprietary & Confidential Information.

Optio3 Hub APIs
APIs and Definitions for the Optio3 Hub product.

OpenAPI spec version: 1.0.0


NOTE: This class is auto generated by the swagger code generator program.
https://github.com/swagger-api/swagger-codegen.git
Do not edit the class manually.
"""


from pprint import pformat
from six import iteritems
import re

class SearchRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, query=None, filters=None, scope_to_filters=None):
        """
        SearchRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'query': 'str',
            'filters': 'list[SearchRequestFilters]',
            'scope_to_filters': 'bool'
        }

        self.attribute_map = {
            'query': 'query',
            'filters': 'filters',
            'scope_to_filters': 'scopeToFilters'
        }

        self._query = query
        self._filters = filters
        self._scope_to_filters = scope_to_filters


    @property
    def query(self):
        """
        Gets the query of this SearchRequest.

        :return: The query of this SearchRequest.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """
        Sets the query of this SearchRequest.

        :param query: The query of this SearchRequest.
        :type: str
        """

        self._query = query

    @property
    def filters(self):
        """
        Gets the filters of this SearchRequest.

        :return: The filters of this SearchRequest.
        :rtype: list[SearchRequestFilters]
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """
        Sets the filters of this SearchRequest.

        :param filters: The filters of this SearchRequest.
        :type: list[SearchRequestFilters]
        """

        self._filters = filters

    @property
    def scope_to_filters(self):
        """
        Gets the scope_to_filters of this SearchRequest.

        :return: The scope_to_filters of this SearchRequest.
        :rtype: bool
        """
        return self._scope_to_filters

    @scope_to_filters.setter
    def scope_to_filters(self, scope_to_filters):
        """
        Sets the scope_to_filters of this SearchRequest.

        :param scope_to_filters: The scope_to_filters of this SearchRequest.
        :type: bool
        """

        self._scope_to_filters = scope_to_filters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SearchRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
