# coding: utf-8

"""
Copyright (C) 2017-2018, Optio3, Inc. All Rights Reserved.

Proprietary & Confidential Information.

Optio3 Hub APIs
APIs and Definitions for the Optio3 Hub product.

OpenAPI spec version: 1.0.0


NOTE: This class is auto generated by the swagger code generator program.
https://github.com/swagger-api/swagger-codegen.git
Do not edit the class manually.
"""

class TimeRangeId:
    LAST15MINUTES = "Last15Minutes"
    LAST30MINUTES = "Last30Minutes"
    LAST60MINUTES = "Last60Minutes"
    HOUR = "Hour"
    PREVIOUSHOUR = "PreviousHour"
    LAST3HOURS = "Last3Hours"
    LAST6HOURS = "Last6Hours"
    LAST12HOURS = "Last12Hours"
    LAST24HOURS = "Last24Hours"
    TODAY = "Today"
    YESTERDAY = "Yesterday"
    LAST2DAYS = "Last2Days"
    LAST3DAYS = "Last3Days"
    LAST7DAYS = "Last7Days"
    WEEK = "Week"
    PREVIOUSWEEK = "PreviousWeek"
    MONTH = "Month"
    PREVIOUSMONTH = "PreviousMonth"
    LAST30DAYS = "Last30Days"
    QUARTER = "Quarter"
    PREVIOUSQUARTER = "PreviousQuarter"
    LAST3MONTHS = "Last3Months"
    YEAR = "Year"
    PREVIOUSYEAR = "PreviousYear"
    LAST365DAYS = "Last365Days"
    ALL = "All"
