/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 */
package com.optio3.protocol.model.bacnet.enums;

import javax.annotation.Nonnull;

import com.optio3.serialization.HandlerForDecoding;
import com.optio3.serialization.HandlerForEncoding;
import com.optio3.serialization.TypedBitSet;
import org.apache.commons.lang3.StringUtils;

public enum BACnetPropertyIdentifier implements TypedBitSet.ValueGetter
{
    // @formatter:off
    absentee_limit                      (244),
    accepted_modes                      (175),
    access_alarm_events                 (245),
    access_doors                        (246),
    access_event                        (247),
    access_event_authentication_factor  (248),
    access_event_credential             (249),
    access_event_tag                    (322),
    access_event_time                   (250),
    access_transaction_events           (251),
    accompaniment                       (252),
    accompaniment_time                  (253),
    ack_required                        (1),
    acked_transitions                   (0),
    action                              (2),
    action_text                         (3),
    activation_time                     (254),
    active_authentication_policy        (255),
    active_cov_multiple_subscriptions   (481),
    active_cov_subscriptions            (152),
    active_text                         (4),
    active_vt_sessions                  (5),
    actual_shed_level                   (212),
    adjust_value                        (176),
    alarm_value                         (6),
    alarm_values                        (7),
    align_intervals                     (193),
    all                                 (8),
    all_writes_successful               (9),
    allow_group_delay_inhibit           (365),
    apdu_length                         (399),
    apdu_segment_timeout                (10),
    apdu_timeout                        (11),
    application_software_version        (12),
    archive                             (13),
    assigned_access_rights              (256),
    assigned_landing_calls              (447),
    attempted_samples                   (124),
    authentication_factors              (257),
    authentication_policy_list          (258),
    authentication_policy_names         (259),
    authentication_status               (260),
    authorization_exemptions            (364),
    authorization_mode                  (261),
    auto_slave_discovery                (169),
    average_value                       (125),
    backup_and_restore_state            (338),
    backup_failure_timeout              (153),
    backup_preparation_time             (339),
    bacnet_ip_global_address            (407),
    bacnet_ip_mode                      (408),
    bacnet_ip_multicast_address         (409),
    bacnet_ip_nat_traversal             (410),
    bacnet_ip_udp_port                  (412),
    bacnet_ipv6_mode                    (435),
    bacnet_ipv6_udp_port                (438),
    bacnet_ipv6_multicast_address       (440),
    base_device_security_policy         (327),
    bbmd_accept_fd_registrations        (413),
    bbmd_broadcast_distribution_table   (414),
    bbmd_foreign_device_table           (415),
    belongs_to                          (262),
    bias                                (14),
    bit_mask                            (342),
    bit_text                            (343),
    blink_warn_enable                   (373),
    buffer_size                         (126),
    car_assigned_direction              (448),
    car_door_command                    (449),
    car_door_status                     (450),
    car_door_text                       (451),
    car_door_zone                       (452),
    car_drive_status                    (453),
    car_load                            (454),
    car_load_units                      (455),
    car_mode                            (456),
    car_moving_direction                (457),
    car_position                        (458),
    change_of_state_count               (15),
    change_of_state_time                (16),
    changes_pending                     (416),
    channel_number                      (366),
    client_cov_increment                (127),
    command                             (417),
    command_time_array                  (430),
    configuration_files                 (154),
    control_groups                      (367),
    controlled_variable_reference       (19),
    controlled_variable_units           (20),
    controlled_variable_value           (21),
    count                               (177),
    count_before_change                 (178),
    count_change_time                   (179),
    cov_increment                       (22),
    cov_period                          (180),
    cov_resubscription_interval         (128),
    covu_period                         (349),
    covu_recipients                     (350),
    credential_disable                  (263),
    credential_status                   (264),
    credentials                         (265),
    credentials_in_zone                 (266),
    current_command_priority            (431),
    database_revision                   (155),
    date_list                           (23),
    daylight_savings_status             (24),
    days_remaining                      (267),
    deadband                            (25),
    default_fade_time                   (374),
    default_ramp_rate                   (375),
    default_step_increment              (376),
    default_subordinate_relationship    (490),
    default_timeout                     (393),
    deployed_profile_location           (484),
    derivative_constant                 (26),
    derivative_constant_units           (27),
    description                         (28),
    description_of_halt                 (29),
    device_address_binding              (30),
    device_type                         (31),
    direct_reading                      (156),
    distribution_key_revision           (328),
    do_not_hide                         (329),
    door_alarm_state                    (226),
    door_extended_pulse_time            (227),
    door_members                        (228),
    door_open_too_long_time             (229),
    door_pulse_time                     (230),
    door_status                         (231),
    door_unlock_delay_time              (232),
    duty_window                         (213),
    effective_period                    (32),
    egress_active                       (386),
    egress_time                         (377),
    elapsed_active_time                 (33),
    elevator_group                      (459),
    enable                              (133),
    energy_meter                        (460),
    energy_meter_ref                    (461),
    entry_points                        (268),
    error_limit                         (34),
    escalator_mode                      (462),
    event_algorithm_inhibit             (354),
    event_algorithm_inhibit_ref         (355),
    event_detection_enable              (353),
    event_enable                        (35),
    event_message_texts                 (351),
    event_message_texts_config          (352),
    event_parameters                    (83),
    event_state                         (36),
    event_time_stamps                   (130),
    event_type                          (37),
    exception_schedule                  (38),
    execution_delay                     (368),
    exit_points                         (269),
    expected_shed_level                 (214),
    expiration_time                     (270),
    extended_time_enable                (271),
    failed_attempt_events               (272),
    failed_attempts                     (273),
    failed_attempts_time                (274),
    fault_high_limit                    (388),
    fault_low_limit                     (389),
    fault_parameters                    (358),
    fault_signals                       (463),
    fault_type                          (359),
    fault_values                        (39),
    fd_bbmd_address                     (418),
    fd_subscription_lifetime            (419),
    feedback_value                      (40),
    file_access_method                  (41),
    file_size                           (42),
    file_type                           (43),
    firmware_revision                   (44),
    floor_text                          (464),
    full_duty_baseline                  (215),
    global_identifier                   (323),
    group_id                            (465),
    group_member_names                  (346),
    group_members                       (345),
    group_mode                          (467),
    high_limit                          (45),
    higher_deck                         (468),
    in_process                          (47),
    in_progress                         (378),
    inactive_text                       (46),
    initial_timeout                     (394),
    input_reference                     (181),
    installation_id                     (469),
    instance_of                         (48),
    instantaneous_power                 (379),
    integral_constant                   (49),
    integral_constant_units             (50),
    interface_value                     (387),
    interval_offset                     (195),
    ip_address                          (400),
    ip_default_gateway                  (401),
    ip_dhcp_enable                      (402),
    ip_dhcp_lease_time                  (403),
    ip_dhcp_lease_time_remaining        (404),
    ip_dhcp_server                      (405),
    ip_dns_server                       (406),
    ip_subnet_mask                      (411),
    ipv6_address                        (436),
    ipv6_auto_addressing_enable         (442),
    ipv6_default_gateway                (439),
    ipv6_dhcp_lease_time                (443),
    ipv6_dhcp_lease_time_remaining      (444),
    ipv6_dhcp_server                    (445),
    ipv6_dns_server                     (441),
    ipv6_prefix_length                  (437),
    ipv6_zone_index                     (446),
    is_utc                              (344),
    key_sets                            (330),
    landing_call_control                (471),
    landing_calls                       (470),
    landing_door_status                 (472),
    last_access_event                   (275),
    last_access_point                   (276),
    last_command_time                   (432),
    last_credential_added               (277),
    last_credential_added_time          (278),
    last_credential_removed             (279),
    last_credential_removed_time        (280),
    last_key_server                     (331),
    last_notify_record                  (173),
    last_priority                       (369),
    last_restart_reason                 (196),
    last_restore_time                   (157),
    last_state_change                   (395),
    last_use_time                       (281),
    life_safety_alarm_values            (166),
    lighting_command                    (380),
    lighting_command_default_priority   (381),
    limit_enable                        (52),
    limit_monitoring_interval           (182),
    link_speed                          (420),
    link_speed_autonegotiate            (422),
    link_speeds                         (421),
    list_of_group_members               (53),
    list_of_object_property_references  (54),
    local_date                          (56),
    local_forwarding_only               (360),
    local_time                          (57),
    location                            (58),
    lock_status                         (233),
    lockout                             (282),
    lockout_relinquish_time             (283),
    log_buffer                          (131),
    log_device_object_property          (132),
    log_interval                        (134),
    logging_object                      (183),
    logging_record                      (184),
    logging_type                        (197),
    low_diff_limit                      (390),
    low_limit                           (59),
    lower_deck                          (473),
    mac_address                         (423),
    machine_room_id                     (474),
    maintenance_required                (158),
    making_car_call                     (475),
    manipulated_variable_reference      (60),
    manual_slave_address_binding        (170),
    masked_alarm_values                 (234),
    max_actual_value                    (382),
    max_apdu_length_accepted            (62),
    max_failed_attempts                 (285),
    max_info_frames                     (63),
    max_master                          (64),
    max_pres_value                      (65),
    max_segments_accepted               (167),
    maximum_output                      (61),
    maximum_value                       (135),
    maximum_value_timestamp             (149),
    member_of                           (159),
    member_status_flags                 (347),
    members                             (286),
    min_actual_value                    (383),
    min_pres_value                      (69),
    minimum_off_time                    (66),
    minimum_on_time                     (67),
    minimum_output                      (68),
    minimum_value                       (136),
    minimum_value_timestamp             (150),
    mode                                (160),
    model_name                          (70),
    modification_date                   (71),
    muster_point                        (287),
    negative_access_rules               (288),
    network_access_security_policies    (332),
    network_interface_name              (424),
    network_number                      (425),
    network_number_quality              (426),
    network_type                        (427),
    next_stopping_floor                 (476),
    node_subtype                        (207),
    node_type                           (208),
    notification_class                  (17),
    notification_threshold              (137),
    notify_type                         (72),
    number_of_apdu_retries              (73),
    number_of_authentication_policies   (289),
    number_of_states                    (74),
    object_identifier                   (75),
    object_list                         (76),
    object_name                         (77),
    object_property_reference           (78),
    object_type                         (79),
    occupancy_count                     (290),
    occupancy_count_adjust              (291),
    occupancy_count_enable              (292),
    occupancy_lower_limit               (294),
    occupancy_lower_limit_enforced      (295),
    occupancy_state                     (296),
    occupancy_upper_limit               (297),
    occupancy_upper_limit_enforced      (298),
    operation_direction                 (477),
    operation_expected                  (161),
    optional                            (80),
    out_of_service                      (81),
    output_units                        (82),
    packet_reorder_time                 (333),
    passback_mode                       (300),
    passback_timeout                    (301),
    passenger_alarm                     (478),
    polarity                            (84),
    port_filter                         (363),
    positive_access_rules               (302),
    power                               (384),
    power_mode                          (479),
    prescale                            (185),
    present_value                       (85),
    priority                            (86),
    priority_array                      (87),
    priority_for_writing                (88),
    process_identifier                  (89),
    process_identifier_filter           (361),
    profile_location                    (485),
    profile_name                        (168),
    program_change                      (90),
    program_location                    (91),
    program_state                       (92),
    property_list                       (371, 14),
    proportional_constant               (93),
    proportional_constant_units         (94),
    protocol_level                      (482),
    protocol_object_types_supported     (96),
    protocol_revision                   (139),
    protocol_services_supported         (97),
    protocol_version                    (98),
    pulse_rate                          (186),
    read_only                           (99),
    reason_for_disable                  (303),
    reason_for_halt                     (100),
    recipient_list                      (102),
    record_count                        (141),
    records_since_notification          (140),
    reference_port                      (483),
    registered_car_call                 (480),
    reliability                         (103),
    reliability_evaluation_inhibit      (357),
    relinquish_default                  (104),
    represents                          (491),
    requested_shed_level                (218),
    requested_update_interval           (348),
    required                            (105),
    resolution                          (106),
    restart_notification_recipients     (202),
    restore_completion_time             (340),
    restore_preparation_time            (341),
    routing_table                       (428),
    scale                               (187),
    scale_factor                        (188),
    schedule_default                    (174),
    secured_status                      (235),
    security_pdu_timeout                (334),
    security_time_window                (335),
    segmentation_supported              (107),
    serial_number                       (372),
    setpoint                            (108),
    setpoint_reference                  (109),
    setting                             (162),
    shed_duration                       (219),
    shed_level_descriptions             (220),
    shed_levels                         (221),
    silenced                            (163),
    slave_address_binding               (171),
    slave_proxy_enable                  (172),
    start_time                          (142),
    state_change_values                 (396),
    state_description                   (222),
    state_text                          (110),
    status_flags                        (111),
    stop_time                           (143),
    stop_when_full                      (144),
    strike_count                        (391),
    structured_object_list              (209),
    subordinate_annotations             (210),
    subordinate_list                    (211),
    subordinate_node_types              (487),
    subordinate_relationships           (489),
    subordinate_tags                    (488),
    subscribed_recipients               (362),
    supported_format_classes            (305),
    supported_formats                   (304),
    supported_security_algorithms       (336),
    system_status                       (112),
    tags                                (486),
    threat_authority                    (306),
    threat_level                        (307),
    time_delay                          (113),
    time_delay_normal                   (356),
    time_of_active_time_reset           (114),
    time_of_device_restart              (203),
    time_of_state_count_reset           (115),
    time_of_strike_count_reset          (392),
    time_synchronization_interval       (204),
    time_synchronization_recipients     (116),
    timer_running                       (397),
    timer_state                         (398),
    total_record_count                  (145),
    trace_flag                          (308),
    tracking_value                      (164),
    transaction_notification_class      (309),
    transition                          (385),
    trigger                             (205),
    units                               (117),
    update_interval                     (118),
    update_key_set_timeout              (337),
    update_time                         (189),
    user_external_identifier            (310),
    user_information_reference          (311),
    user_name                           (317),
    user_type                           (318),
    uses_remaining                      (319),
    utc_offset                          (119),
    utc_time_synchronization_recipients (206),
    valid_samples                       (146),
    value_before_change                 (190),
    value_change_time                   (192),
    value_set                           (191),
    value_source                        (433),
    value_source_array                  (434),
    variance_value                      (151),
    vendor_identifier                   (120),
    vendor_name                         (121),
    verification_time                   (326),
    virtual_mac_address_table           (429),
    vt_classes_supported                (122),
    weekly_schedule                     (123),
    window_interval                     (147),
    window_samples                      (148),
    write_status                        (370),
    zone_from                           (320),
    zone_members                        (165),
    zone_to                             (321);
    // @formatter:on

    private final short                             m_encoding;
    private final BACnetPropertyIdentifierOrUnknown m_singleton;
    private final int                               m_revision;
    private final String                            m_displayName;

    BACnetPropertyIdentifier(int encoding)
    {
        this(encoding, 0);
    }

    BACnetPropertyIdentifier(int encoding,
                             int revision)
    {
        m_encoding = (short) encoding;
        m_singleton = new BACnetPropertyIdentifierOrUnknown(this);
        m_revision = revision;

        String[] parts = StringUtils.split(this.name(), '_');
        for (int i = 0; i < parts.length; i++)
        {
            parts[i] = StringUtils.capitalize(parts[i]);
        }

        m_displayName = String.join(" ", parts);
    }

    public static BACnetPropertyIdentifier parse(String value)
    {
        return BACnetPropertyIdentifierOrUnknown.parseCached(value);
    }

    @HandlerForDecoding
    public static BACnetPropertyIdentifier parse(short value)
    {
        return BACnetPropertyIdentifierOrUnknown.parseCached(value);
    }

    @HandlerForEncoding
    public short encoding()
    {
        return m_encoding;
    }

    @Override
    public int getEncodingValue()
    {
        return m_encoding;
    }

    @Nonnull
    public BACnetPropertyIdentifierOrUnknown forRequest()
    {
        return m_singleton;
    }

    public int getRevision()
    {
        return m_revision;
    }

    public String getDisplayName()
    {
        return m_displayName;
    }
}
