/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class AlertEngineOperatorUnaryAssetGraphNodes extends models.EngineExpressionFromAlerts {
    constructor() {
        super();
        this.setDiscriminator("AlertEngineOperatorUnaryAssetGraphNodes");
    }

    getFixupPrototypeFunction() { return AlertEngineOperatorUnaryAssetGraphNodes.fixupPrototype; }

    static newInstance(model: Partial<AlertEngineOperatorUnaryAssetGraphNodes>): AlertEngineOperatorUnaryAssetGraphNodes {
        let obj = Object.assign(new AlertEngineOperatorUnaryAssetGraphNodes(), model);
        AlertEngineOperatorUnaryAssetGraphNodes.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AlertEngineOperatorUnaryAssetGraphNodes>): AlertEngineOperatorUnaryAssetGraphNodes {
        if (!model) return null;
        return AlertEngineOperatorUnaryAssetGraphNodes.newInstance(<AlertEngineOperatorUnaryAssetGraphNodes> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AlertEngineOperatorUnaryAssetGraphNodes) {
        models.EngineExpressionFromAlerts.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    nodeId: string;

}
