/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class AssetGraphBinding {
    getFixupPrototypeFunction() { return AssetGraphBinding.fixupPrototype; }

    static newInstance(model: Partial<AssetGraphBinding>): AssetGraphBinding {
        let obj = Object.assign(new AssetGraphBinding(), model);
        AssetGraphBinding.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<AssetGraphBinding>): AssetGraphBinding {
        if (!model) return null;
        return AssetGraphBinding.newInstance(<AssetGraphBinding> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: AssetGraphBinding) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.AssetGraphBinding.prototype);

        obj.fixupFields();
    }

    fixupFields() {
    }

    graphId: string;

    nodeId: string;

    selectorId: string;

}
