/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class BACnetImportExportData extends models.ImportExportData {
    constructor() {
        super();
        this.setDiscriminator("BACnetImportExportData");
    }

    getFixupPrototypeFunction() { return BACnetImportExportData.fixupPrototype; }

    static newInstance(model: Partial<BACnetImportExportData>): BACnetImportExportData {
        let obj = Object.assign(new BACnetImportExportData(), model);
        BACnetImportExportData.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<BACnetImportExportData>): BACnetImportExportData {
        if (!model) return null;
        return BACnetImportExportData.newInstance(<BACnetImportExportData> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: BACnetImportExportData) {
        models.ImportExportData.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (this.networkId === undefined) {
            this.networkId = 0;
        }
        if (this.instanceId === undefined) {
            this.instanceId = 0;
        }
        if (this.transport) {
            models.TransportAddress.fixupPrototype(this.transport);
        }
    }

    networkId: number;

    instanceId: number;

    objectId: string;

    transport: models.TransportAddress;

}
