/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class DashboardBannerSegment {
    getFixupPrototypeFunction() { return DashboardBannerSegment.fixupPrototype; }

    static newInstance(model: Partial<DashboardBannerSegment>): DashboardBannerSegment {
        let obj = Object.assign(new DashboardBannerSegment(), model);
        DashboardBannerSegment.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DashboardBannerSegment>): DashboardBannerSegment {
        if (!model) return null;
        return DashboardBannerSegment.newInstance(<DashboardBannerSegment> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DashboardBannerSegment) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.DashboardBannerSegment.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.widthRatio === undefined) {
            this.widthRatio = 0;
        }
        if (this.branding) {
            models.BrandingConfiguration.fixupPrototype(this.branding);
        }
    }

    widthRatio: number;

    branding: models.BrandingConfiguration;

}
