/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class DeviceElementFilterRequest extends models.AssetFilterRequest {
    constructor() {
        super();
        this.setDiscriminator("DeviceElementFilterRequest");
    }

    getFixupPrototypeFunction() { return DeviceElementFilterRequest.fixupPrototype; }

    static newInstance(model: Partial<DeviceElementFilterRequest>): DeviceElementFilterRequest {
        let obj = Object.assign(new DeviceElementFilterRequest(), model);
        DeviceElementFilterRequest.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<DeviceElementFilterRequest>): DeviceElementFilterRequest {
        if (!model) return null;
        return DeviceElementFilterRequest.newInstance(<DeviceElementFilterRequest> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: DeviceElementFilterRequest) {
        models.AssetFilterRequest.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    hasNoSampling: boolean;

    hasAnySampling: boolean;

}
