/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class EngineStatementFunctionReturnValue extends models.EngineStatementFromCore {
    constructor() {
        super();
        this.setDiscriminator("EngineStatementFunctionReturnValue");
    }

    getFixupPrototypeFunction() { return EngineStatementFunctionReturnValue.fixupPrototype; }

    static newInstance(model: Partial<EngineStatementFunctionReturnValue>): EngineStatementFunctionReturnValue {
        let obj = Object.assign(new EngineStatementFunctionReturnValue(), model);
        EngineStatementFunctionReturnValue.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EngineStatementFunctionReturnValue>): EngineStatementFunctionReturnValue {
        if (!model) return null;
        return EngineStatementFunctionReturnValue.newInstance(<EngineStatementFunctionReturnValue> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EngineStatementFunctionReturnValue) {
        models.EngineStatementFromCore.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (this.value) {
            models.EngineBlock.fixupPrototype(this.value);
        }
    }

    value: models.EngineExpression;

}
