/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class EngineValueListConcrete extends models.EngineValueList {
    constructor() {
        super();
        this.setDiscriminator("EngineValueListConcrete");
    }

    getFixupPrototypeFunction() { return EngineValueListConcrete.fixupPrototype; }

    static newInstance(model: Partial<EngineValueListConcrete>): EngineValueListConcrete {
        let obj = Object.assign(new EngineValueListConcrete(), model);
        EngineValueListConcrete.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<EngineValueListConcrete>): EngineValueListConcrete {
        if (!model) return null;
        return EngineValueListConcrete.newInstance(<EngineValueListConcrete> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: EngineValueListConcrete) {
        models.EngineValueList.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (this.elements) {
            for (let val of this.elements) {
                models.EngineValue.fixupPrototype(val);
            }
        }
    }

    elements: Array<models.EngineValue>;

}
