/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class FilteredSubnet {
    getFixupPrototypeFunction() { return FilteredSubnet.fixupPrototype; }

    static newInstance(model: Partial<FilteredSubnet>): FilteredSubnet {
        let obj = Object.assign(new FilteredSubnet(), model);
        FilteredSubnet.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<FilteredSubnet>): FilteredSubnet {
        if (!model) return null;
        return FilteredSubnet.newInstance(<FilteredSubnet> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: FilteredSubnet) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.FilteredSubnet.prototype);

        obj.fixupFields();
    }

    fixupFields() {
    }

    cidr: string;

    notes: string;

}
