/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export enum HierarchicalVisualizationType {
    HEATMAP = 'HEATMAP',
    LINE = 'LINE',
    TABLE = 'TABLE',
    TABLE_WITH_BAR = 'TABLE_WITH_BAR',
    BUBBLEMAP = 'BUBBLEMAP',
    TREEMAP = 'TREEMAP',
    SUNBURST = 'SUNBURST',
    PIEBURST = 'PIEBURST',
    DONUT = 'DONUT',
    PIE = 'PIE'
}
