/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class MbControlListSubscriptions extends models.MbControl {
    constructor() {
        super();
        this.setDiscriminator("MbControlListSubscriptions");
    }

    getFixupPrototypeFunction() { return MbControlListSubscriptions.fixupPrototype; }

    static newInstance(model: Partial<MbControlListSubscriptions>): MbControlListSubscriptions {
        let obj = Object.assign(new MbControlListSubscriptions(), model);
        MbControlListSubscriptions.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<MbControlListSubscriptions>): MbControlListSubscriptions {
        if (!model) return null;
        return MbControlListSubscriptions.newInstance(<MbControlListSubscriptions> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: MbControlListSubscriptions) {
        models.MbControl.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

}
