/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class NetworkDescriptor extends models.BaseAssetDescriptor {
    constructor() {
        super();
        this.setDiscriminator("NetworkDescriptor");
    }

    getFixupPrototypeFunction() { return NetworkDescriptor.fixupPrototype; }

    static newInstance(model: Partial<NetworkDescriptor>): NetworkDescriptor {
        let obj = Object.assign(new NetworkDescriptor(), model);
        NetworkDescriptor.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<NetworkDescriptor>): NetworkDescriptor {
        if (!model) return null;
        return NetworkDescriptor.newInstance(<NetworkDescriptor> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: NetworkDescriptor) {
        models.BaseAssetDescriptor.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    sysId: string;

}
