/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class NormalizationEngineOperatorUnaryGetControllerProperty extends models.EngineOperatorUnaryFromNormalization {
    constructor() {
        super();
        this.setDiscriminator("NormalizationEngineOperatorUnaryGetControllerProperty");
    }

    getFixupPrototypeFunction() { return NormalizationEngineOperatorUnaryGetControllerProperty.fixupPrototype; }

    static newInstance(model: Partial<NormalizationEngineOperatorUnaryGetControllerProperty>): NormalizationEngineOperatorUnaryGetControllerProperty {
        let obj = Object.assign(new NormalizationEngineOperatorUnaryGetControllerProperty(), model);
        NormalizationEngineOperatorUnaryGetControllerProperty.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<NormalizationEngineOperatorUnaryGetControllerProperty>): NormalizationEngineOperatorUnaryGetControllerProperty {
        if (!model) return null;
        return NormalizationEngineOperatorUnaryGetControllerProperty.newInstance(<NormalizationEngineOperatorUnaryGetControllerProperty> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: NormalizationEngineOperatorUnaryGetControllerProperty) {
        models.EngineOperatorUnaryFromNormalization.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
    }

    property: models.NormalizationEngineValueControllerPropertyType;

}
