/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class ProberOperationForBACnetToDiscoverRoutersRouterNetwork {
    getFixupPrototypeFunction() { return ProberOperationForBACnetToDiscoverRoutersRouterNetwork.fixupPrototype; }

    static newInstance(model: Partial<ProberOperationForBACnetToDiscoverRoutersRouterNetwork>): ProberOperationForBACnetToDiscoverRoutersRouterNetwork {
        let obj = Object.assign(new ProberOperationForBACnetToDiscoverRoutersRouterNetwork(), model);
        ProberOperationForBACnetToDiscoverRoutersRouterNetwork.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<ProberOperationForBACnetToDiscoverRoutersRouterNetwork>): ProberOperationForBACnetToDiscoverRoutersRouterNetwork {
        if (!model) return null;
        return ProberOperationForBACnetToDiscoverRoutersRouterNetwork.newInstance(<ProberOperationForBACnetToDiscoverRoutersRouterNetwork> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: ProberOperationForBACnetToDiscoverRoutersRouterNetwork) {
        if (!obj) return;

        Object.setPrototypeOf(obj, models.ProberOperationForBACnetToDiscoverRoutersRouterNetwork.prototype);

        obj.fixupFields();
    }

    fixupFields() {
        if (this.device) {
            models.BaseAssetDescriptor.fixupPrototype(this.device);
        }
    }

    device: models.BACnetDeviceDescriptor;

    networks: Array<number>;

}
