/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class ProberObjectIpn extends models.ProberObject {
    constructor() {
        super();
        this.setDiscriminator("ProberObjectIpn");
    }

    getFixupPrototypeFunction() { return ProberObjectIpn.fixupPrototype; }

    static newInstance(model: Partial<ProberObjectIpn>): ProberObjectIpn {
        let obj = Object.assign(new ProberObjectIpn(), model);
        ProberObjectIpn.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<ProberObjectIpn>): ProberObjectIpn {
        if (!model) return null;
        return ProberObjectIpn.newInstance(<ProberObjectIpn> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: ProberObjectIpn) {
        models.ProberObject.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (typeof this.timestamp === "string") {
            this.timestamp = new Date(<string><any>this.timestamp);
        }
    }

    timestamp: Date;

}
