/**
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class TransportNetworkDescriptor extends models.BaseAssetDescriptor {
    constructor() {
        super();
        this.setDiscriminator("TransportNetworkDescriptor");
    }

    getFixupPrototypeFunction() { return TransportNetworkDescriptor.fixupPrototype; }

    static newInstance(model: Partial<TransportNetworkDescriptor>): TransportNetworkDescriptor {
        let obj = Object.assign(new TransportNetworkDescriptor(), model);
        TransportNetworkDescriptor.fixupPrototype(obj);
        return obj;
    }

    static deepClone(model: Partial<TransportNetworkDescriptor>): TransportNetworkDescriptor {
        if (!model) return null;
        return TransportNetworkDescriptor.newInstance(<TransportNetworkDescriptor> JSON.parse(JSON.stringify(model)));
    }

    static fixupPrototype(obj: TransportNetworkDescriptor) {
        models.BaseAssetDescriptor.fixupPrototype(obj);
    }

    fixupFields() {
        super.fixupFields();
        if (this.networkNumber === undefined) {
            this.networkNumber = 0;
        }
    }

    transportAddress: string;

    networkNumber: number;

    deviceIdentifier: string;

}
