/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.cloud.client.hub.api;

import com.optio3.cloud.client.hub.model.InstanceConfiguration;
import com.optio3.cloud.client.hub.model.LoggerConfiguration;
import com.optio3.cloud.client.hub.model.MessageBusDatagramSession;
import com.optio3.cloud.client.hub.model.RecordIdentity;
import com.optio3.cloud.client.hub.model.UsageFilterRequest;
import com.optio3.cloud.client.hub.model.UsageFilterResponse;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import org.apache.cxf.jaxrs.ext.multipart.*;
import org.apache.cxf.jaxrs.ext.PATCH;

@Path("/")
public interface AdminTasksApi
{
    @GET
    @Path("/admin-tasks/upgrade/list")
    @Produces(
    {
        "application/json"
    })
    public List<String> checkUpgradeLevel();

    @POST
    @Path("/admin-tasks/check-usages")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public UsageFilterResponse checkUsages(UsageFilterRequest body);

    @GET
    @Path("/admin-tasks/compact-time-series")
    @Produces(
    {
        "text/plain"
    })
    public String compactTimeSeries(@QueryParam("force") Boolean force);

    @POST
    @Path("/admin-tasks/loggers/config")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public LoggerConfiguration configLogger(LoggerConfiguration body);

    @POST
    @Path("/admin-tasks/loggers/config-gateway/{gatewaySysId}")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public LoggerConfiguration configLoggerForGateway(@PathParam("gatewaySysId") String gatewaySysId, LoggerConfiguration body);

    @DELETE
    @Path("/admin-tasks/backup/item/{id}")
    public String deleteBackup(@PathParam("id") String id);

    @GET
    @Path("/admin-tasks/drop-network-stats")
    public String dropNetworkStats(@QueryParam("compact") Boolean compact);

    @GET
    @Path("/admin-tasks/db-connections")
    @Produces(
    {
        "text/plain"
    })
    public String dumpDbConnections();

    @GET
    @Path("/admin-tasks/message-bus-stats")
    @Produces(
    {
        "text/plain"
    })
    public String dumpMessageBusStatistics();

    @GET
    @Path("/admin-tasks/request-stats")
    @Produces(
    {
        "text/plain"
    })
    public String dumpRequestStatistics();

    @GET
    @Path("/admin-tasks/rpc-stats")
    @Produces(
    {
        "text/plain"
    })
    public String dumpRpcStatistics();

    @GET
    @Path("/admin-tasks/threads")
    @Produces(
    {
        "text/plain"
    })
    public String dumpThreads();

    @GET
    @Path("/admin-tasks/logger/flush")
    @Produces(
    {
        "application/json"
    })
    public String flushLogger(@QueryParam("toConsole") Boolean toConsole);

    @GET
    @Path("/admin-tasks/query-plan-cache/flush")
    @Produces(
    {
        "text/plain"
    })
    public String flushQueryPlanCache();

    @GET
    @Path("/admin-tasks/spooler/flush")
    @Produces(
    {
        "text/plain"
    })
    public String flushSpooler();

    @GET
    @Path("/admin-tasks/app-version")
    @Produces(
    {
        "text/plain"
    })
    public String getAppVersion();

    @GET
    @Path("/admin-tasks/backup/item/{id}")
    public String getBackup(@PathParam("id") String id);

    @GET
    @Path("/admin-tasks/db/get-variable")
    @Produces(
    {
        "application/json"
    })
    public String getDatabaseVariable(@QueryParam("name") String name);

    @GET
    @Path("/admin-tasks/datagram-sessions")
    @Produces(
    {
        "application/json"
    })
    public List<MessageBusDatagramSession> getDatagramSessions();

    @GET
    @Path("/admin-tasks/instance-config")
    @Produces(
    {
        "application/json"
    })
    public InstanceConfiguration getInstanceConfiguration();

    @GET
    @Path("/admin-tasks/loggers/list")
    @Produces(
    {
        "application/json"
    })
    public List<LoggerConfiguration> getLoggers();

    @GET
    @Path("/admin-tasks/loggers/list-gateway/{gatewaySysId}")
    @Produces(
    {
        "application/json"
    })
    public List<LoggerConfiguration> getLoggersForGateway(@PathParam("gatewaySysId") String gatewaySysId);

    @GET
    @Path("/admin-tasks/db/list-variables")
    @Produces(
    {
        "application/json"
    })
    public List<String> listDatabaseVariables();

    @GET
    @Path("/admin-tasks/logger/pending")
    @Produces(
    {
        "application/json"
    })
    public Integer pendingLogEntries();

    @POST
    @Path("/admin-tasks/report-crash")
    @Consumes(
    {
        "application/x-www-form-urlencoded"
    })
    @Produces(
    {
        "text/plain"
    })
    public String reportCrash(@FormParam(value = "page") String page, @FormParam(value = "stack") String stack);

    @GET
    @Path("/admin-tasks/db/set-variable/decimal")
    @Produces(
    {
        "application/json"
    })
    public Boolean setDatabaseVariableDecimal(@QueryParam("name") String name, @QueryParam("value") Double value);

    @GET
    @Path("/admin-tasks/db/set-variable/integer")
    @Produces(
    {
        "application/json"
    })
    public Boolean setDatabaseVariableInteger(@QueryParam("name") String name, @QueryParam("value") Long value);

    @GET
    @Path("/admin-tasks/db/set-variable/string")
    @Produces(
    {
        "application/json"
    })
    public Boolean setDatabaseVariableString(@QueryParam("name") String name, @QueryParam("value") String value);

    @GET
    @Path("/admin-tasks/shutdown")
    @Produces(
    {
        "text/plain"
    })
    public String shutdown();

    @GET
    @Path("/admin-tasks/backup/start")
    @Produces(
    {
        "application/json"
    })
    public RecordIdentity startBackup();

}
