/*
 * Copyright (C) 2017-, Optio3, Inc. All Rights Reserved.
 *
 * Proprietary & Confidential Information.
 *
 * Optio3 Hub APIs
 * APIs and Definitions for the Optio3 Hub product.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.optio3.cloud.client.hub.api;

import com.optio3.cloud.client.hub.model.ControllerMetadataAggregation;
import com.optio3.cloud.client.hub.model.DataConnectionSite;
import com.optio3.cloud.client.hub.model.EquipmentAggregation;
import java.io.InputStream;
import com.optio3.cloud.client.hub.model.MetadataAggregation;
import java.time.ZonedDateTime;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.*;
import org.apache.cxf.jaxrs.ext.multipart.*;
import org.apache.cxf.jaxrs.ext.PATCH;

@Path("/")
public interface DataConnectionApi
{
    @GET
    @Path("/data-connection/metadata-aggregation/controller/{controllerId}")
    @Produces(
    {
        "application/json"
    })
    public ControllerMetadataAggregation controllerMetadataAggregation(@PathParam("controllerId") String controllerId, @QueryParam("unclassified") Boolean unclassified, @QueryParam("belowThresholdId") Integer belowThresholdId);

    @GET
    @Path("/data-connection/equipment-aggregation")
    @Produces(
    {
        "application/json"
    })
    public EquipmentAggregation equipmentAggregation();

    @GET
    @Path("/data-connection/connection/{connectionId}/last-sample/{controlPointId}")
    @Produces(
    {
        "application/json"
    })
    public ZonedDateTime getLastSample(@PathParam("connectionId") String connectionId, @PathParam("controlPointId") String controlPointId);

    @GET
    @Path("/data-connection/site")
    @Produces(
    {
        "application/json"
    })
    public DataConnectionSite getSite();

    @GET
    @Path("/data-connection/metadata-aggregation")
    @Produces(
    {
        "application/json"
    })
    public MetadataAggregation metadataAggregation(@QueryParam("unclassified") Boolean unclassified);

    @POST
    @Path("/data-connection/endpoint/{endpointId}")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public JsonNode receiveRaw(@PathParam("endpointId") String endpointId, @QueryParam("arg") String arg, JsonNode body);

    @POST
    @Path("/data-connection/endpoint/{endpointId}/stream")
    @Consumes(
    {
        "application/octet-stream"
    })
    @Produces(
    {
        "application/json"
    })
    public JsonNode receiveStream(@PathParam("endpointId") String endpointId, @QueryParam("arg") String arg, InputStream body);

    @POST
    @Path("/data-connection/connection/{connectionId}/last-sample/{controlPointId}")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public ZonedDateTime setLastSample(@PathParam("connectionId") String connectionId, @PathParam("controlPointId") String controlPointId, ZonedDateTime body);

    @POST
    @Path("/data-connection/site")
    @Consumes(
    {
        "application/json"
    })
    @Produces(
    {
        "application/json"
    })
    public DataConnectionSite setSite(DataConnectionSite body);

}
